FROM node:22-alpine@sha256:b2358485e3e33bc3a33114d2b1bdb18cdbe4df01bd2b257198eb51beb1f026c5

COPY ./zscaler-root-ca.crt* /usr/local/share/ca-certificates/
RUN if [ -f /usr/local/share/ca-certificates/zscaler-root-ca.crt ]; then cat /usr/local/share/ca-certificates/zscaler-root-ca.crt >> /etc/ssl/certs/ca-certificates.crt; fi

RUN apk add --update git bash python3 py3-setuptools make gcc g++ openssh-client curl

ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/zscaler-root-ca.crt
RUN addgroup -S admins
RUN adduser -S releaser -G admins

WORKDIR /app

RUN chown -R releaser:admins /app
USER releaser

COPY ./bin/release.sh ./

CMD ./release.sh
